//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCards()
        {
            this.UsersCards = new HashSet<UsersCards>();
            this.Receipts = new HashSet<Receipts>();
            this.Receipts1 = new HashSet<Receipts>();
        }
    
        public int CardID { get; set; }
        public long CardNumber { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int Cvv2 { get; set; }
        public int Amount { get; set; }
        public string RegisteredPhone { get; set; }
        public int Password { get; set; }
        public string InTheNameOf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersCards> UsersCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts1 { get; set; }
    }
}
