//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCards
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CardID { get; set; }
    
        public virtual CreditCards CreditCards { get; set; }
        public virtual Users Users { get; set; }
    }
}
